/**
 * SPDX-FileCopyrightText: © 2023 Liferay, Inc. <https://liferay.com>
 * SPDX-License-Identifier: BSD-3-Clause
 */

export type Item = {
	[propName: string]: any;

	/**
	 * Label to show.
	 */
	label?: string;

	/**
	 * Global unique id of the item list. Generated by the component.
	 */
	key?: string;

	/**
	 * Hidden value of the item.
	 */
	value?: string;
};

export type Locator = {
	id?: string;
	label: string;
	value: string;
};

export type LastChangeLiveRegion = {
	label: string;
	action: 'removed' | 'added';
};
