/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

import type {Locator} from '@clayui/shared';

export type Item = {

	/**
	 * Global unique id of the item list. Generated by the component.
	 */
	key?: string;

	/**
	 * Label to show.
	 */
	label?: string;

	/**
	 * Hidden value of the item.
	 */
	value?: string;

	[propName: string]: any;
};

export type Locators = {
	id?: Locator;
	label: Locator;
	value: Locator;
};

export type LastChangeLiveRegion = {
	action: 'removed' | 'added';
	label: string;
};
