name: CI
on:
    pull_request:
        branches: ['master']

jobs:
    run:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/setup-node@v1
            - name: Install yarn
              run: npm install -g yarn
            - name: Checkout BASE
              uses: actions/checkout@v2
              with:
                  ref: ${{ github.event.pull_request.base.sha }}
            - name: Install Dependencies
              run: yarn install
            - name: Run Jest
              run: yarn test
            - name: Check Formatting
              run: |
                  yarn lint
                  yarn format:check
            - name: Verify Dependencies
              run: yarn checkDeps
